"""
Data Provider Interface
Provides a clean abstraction for switching between Weaviate vector database and local test data.
"""
import json
import logging
import os
from typing import Any, Optional
from abc import ABC, abstractmethod

logger = logging.getLogger(__name__)


class SearchUnavailableError(Exception):
    """Raised when the search backend (Weaviate) is temporarily unreachable.

    Callers that detect this exception must route the conversation to the RECOVERY
    stage and must not present the zero-result response as a genuine empty match.
    """


class DataProvider(ABC):
    """Abstract base class for data providers."""

    @abstractmethod
    async def get_user_by_id(self, user_id: str) -> Optional[dict[str, Any]]:
        """Get user by ID."""
        pass

    @abstractmethod
    async def search_providers(
        self, query_text: str, limit: int = 3, hyde_text: str = ""
    ) -> list[dict[str, Any]]:
        """Search for service providers."""
        pass

    @abstractmethod
    async def get_provider_by_id(self, provider_id: str) -> Optional[dict[str, Any]]:
        """Get provider by ID."""
        pass


class WeaviateDataProvider(DataProvider):
    """Weaviate-based data provider using vector search."""

    def __init__(self):
        from .weaviate_models import UserModelWeaviate, ProviderModelWeaviate
        self.user_model = UserModelWeaviate
        self.provider_model = ProviderModelWeaviate
        logger.info("Initialized Weaviate data provider")

    async def get_user_by_id(self, user_id: str) -> Optional[dict[str, Any]]:
        """Get user from Weaviate."""
        return self.user_model.get_user_by_id(user_id)

    async def search_providers(
        self, query_text: str, limit: int = 3, hyde_text: str = ""
    ) -> list[dict[str, Any]]:
        """
        Search providers using Weaviate hybrid search.
        Supports both simple text queries and structured JSON queries.

        Args:
            query_text: Search query — can be plain text or a JSON string with keys
                ``available_time``, ``category``, ``criterions``.
            limit: Maximum number of results to return (after any reranking).
            hyde_text: Optional hypothetical profile text generated by LLM (HyDE).
                       Passed to the structured hybrid path to improve vector recall.
        """
        logger.info("Searching providers with query: '%s...'", query_text[:100])

        # Try to parse query_text as JSON for structured search
        try:
            search_request = json.loads(query_text)
            if isinstance(search_request, dict): #and any(k in search_request for k in ['location', 'available_time', 'criterions'])
                # Use structured hybrid search
                logger.info("Using structured hybrid search with request: %s", search_request)
                from .hub_spoke_search import HubSpokeSearch
                providers = HubSpokeSearch.hybrid_search_providers(
                    search_request=search_request,
                    limit=limit,
                    hyde_text=hyde_text,
                )

                logger.info("Returning %s providers from structured search", len(providers))
                return providers
        except (json.JSONDecodeError, ValueError):
            # Not JSON, use simple text search
            logger.info("Query is not JSON, using simple vector search")

        # Use simple vector search for unstructured queries
        providers = self.provider_model.vector_search_providers(query_text, limit)

        logger.info("Returning %s providers from search", len(providers))
        return providers

    async def get_provider_by_id(self, provider_id: str) -> Optional[dict[str, Any]]:
        """Get provider from Weaviate."""
        return self.provider_model.get_provider_by_id(provider_id)


def get_data_provider() -> DataProvider:
    """
    Factory function to get the Weaviate data provider.

    Now exclusively uses Weaviate with Hub and Spoke schema.
    Set WEAVIATE_URL to configure connection (defaults to http://localhost:8090).

    Returns:
        WeaviateDataProvider instance
    """
    weaviate_url = os.getenv('WEAVIATE_URL', 'http://localhost:8090')
    logger.info("Using Weaviate data provider at %s", weaviate_url)
    return WeaviateDataProvider()
