apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: Helm
data:
  use-weaviate: {{ .Values.env.useWeaviate | quote }}
  weaviate-url: {{ .Values.env.weaviateUrl | quote }}
  language-code: {{ .Values.env.languageCode | quote }}
  voice-name: {{ .Values.env.voiceName | quote }}
  host: {{ .Values.env.host | quote }}
  port: {{ .Values.env.port | quote }}
  log-level: {{ .Values.env.logLevel | quote }}
  google-tts-api-concurrency: {{ .Values.env.googleTtsApiConcurrency | quote }}
  debug-record-audio: {{ .Values.env.debugRecordAudio | quote }}
