apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  google-application-credentials: {{ .Values.secrets.googleApplicationCredentialsJson | b64enc }}
  gemini-api-key: {{ .Values.secrets.geminiApiKey | b64enc }}
  google-oauth-client-id: {{ .Values.secrets.googleOauthClientId | b64enc }}
  admin-secret-key: {{ .Values.secrets.adminSecretKey | b64enc }}
