apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
type: Opaque
stringData:
  gemini-api-key: {{ .Values.secrets.geminiApiKey | quote }}
  google-oauth-client-id: {{ .Values.secrets.googleOauthClientId | quote }}
  admin-secret-key: {{ .Values.secrets.adminSecretKey | quote }}
