// Mocks generated by Mockito 5.4.6 from annotations
// in connectx/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i12;

import 'package:async/async.dart' as _i9;
import 'package:connectx/services/speech_service.dart' as _i8;
import 'package:connectx/services/webrtc_service.dart' as _i6;
import 'package:connectx/services/wrappers.dart' as _i13;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:permission_handler/permission_handler.dart' as _i14;
import 'package:stream_channel/stream_channel.dart' as _i3;
import 'package:web_socket_channel/web_socket_channel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWebSocketSink_0 extends _i1.SmartFake implements _i2.WebSocketSink {
  _FakeWebSocketSink_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamChannel_1<T> extends _i1.SmartFake
    implements _i3.StreamChannel<T> {
  _FakeStreamChannel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCSessionDescription_2 extends _i1.SmartFake
    implements _i4.RTCSessionDescription {
  _FakeRTCSessionDescription_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCDataChannel_3 extends _i1.SmartFake
    implements _i4.RTCDataChannel {
  _FakeRTCDataChannel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCDTMFSender_4 extends _i1.SmartFake implements _i4.RTCDTMFSender {
  _FakeRTCDTMFSender_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCRtpSender_5 extends _i1.SmartFake implements _i4.RTCRtpSender {
  _FakeRTCRtpSender_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCRtpTransceiver_6 extends _i1.SmartFake
    implements _i4.RTCRtpTransceiver {
  _FakeRTCRtpTransceiver_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaStream_7 extends _i1.SmartFake implements _i4.MediaStream {
  _FakeMediaStream_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaStreamTrack_8 extends _i1.SmartFake
    implements _i4.MediaStreamTrack {
  _FakeMediaStreamTrack_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCVideoValue_9 extends _i1.SmartFake implements _i4.RTCVideoValue {
  _FakeRTCVideoValue_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCPeerConnection_10 extends _i1.SmartFake
    implements _i4.RTCPeerConnection {
  _FakeRTCPeerConnection_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_11 extends _i1.SmartFake implements _i5.UserMetadata {
  _FakeUserMetadata_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_12 extends _i1.SmartFake implements _i5.MultiFactor {
  _FakeMultiFactor_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_13 extends _i1.SmartFake implements _i5.IdTokenResult {
  _FakeIdTokenResult_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_14 extends _i1.SmartFake
    implements _i5.UserCredential {
  _FakeUserCredential_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_15 extends _i1.SmartFake
    implements _i5.ConfirmationResult {
  _FakeConfirmationResult_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_16 extends _i1.SmartFake implements _i5.User {
  _FakeUser_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCRtpParameters_17 extends _i1.SmartFake
    implements _i4.RTCRtpParameters {
  _FakeRTCRtpParameters_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WebRTCService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebRTCService extends _i1.Mock implements _i6.WebRTCService {
  MockWebRTCService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isConnecting =>
      (super.noSuchMethod(Invocation.getter(#isConnecting), returnValue: false)
          as bool);

  @override
  set onConnected(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onConnected, value),
    returnValueForMissingStub: null,
  );

  @override
  set onDisconnected(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onDisconnected, value),
    returnValueForMissingStub: null,
  );

  @override
  set onRemoteStream(dynamic Function(_i4.MediaStream)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoteStream, value),
        returnValueForMissingStub: null,
      );

  @override
  set onError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i8.SpeechService {
  MockSpeechService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onSpeechStart(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onSpeechStart, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSpeechEnd(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onSpeechEnd, value),
    returnValueForMissingStub: null,
  );

  @override
  set onConnected(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onConnected, value),
    returnValueForMissingStub: null,
  );

  @override
  set onDisconnected(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onDisconnected, value),
    returnValueForMissingStub: null,
  );

  @override
  void stopSpeech() => super.noSuchMethod(
    Invocation.method(#stopSpeech, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> startSpeech() =>
      (super.noSuchMethod(
            Invocation.method(#startSpeech, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [WebSocketChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketChannel extends _i1.Mock implements _i2.WebSocketChannel {
  MockWebSocketChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i2.WebSocketSink get sink =>
      (super.noSuchMethod(
            Invocation.getter(#sink),
            returnValue: _FakeWebSocketSink_0(this, Invocation.getter(#sink)),
          )
          as _i2.WebSocketSink);

  @override
  _i7.Stream<dynamic> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<dynamic>.empty(),
          )
          as _i7.Stream<dynamic>);

  @override
  void pipe(_i3.StreamChannel<dynamic>? other) => super.noSuchMethod(
    Invocation.method(#pipe, [other]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.StreamChannel<S> transform<S>(
    _i3.StreamChannelTransformer<S, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [transformer]),
            returnValue: _FakeStreamChannel_1<S>(
              this,
              Invocation.method(#transform, [transformer]),
            ),
          )
          as _i3.StreamChannel<S>);

  @override
  _i3.StreamChannel<dynamic> transformStream(
    _i7.StreamTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformStream, [transformer]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#transformStream, [transformer]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> transformSink(
    _i9.StreamSinkTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformSink, [transformer]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#transformSink, [transformer]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> changeStream(
    _i7.Stream<dynamic> Function(_i7.Stream<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeStream, [change]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#changeStream, [change]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> changeSink(
    _i7.StreamSink<dynamic> Function(_i7.StreamSink<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeSink, [change]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#changeSink, [change]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<S> cast<S>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _FakeStreamChannel_1<S>(
              this,
              Invocation.method(#cast, []),
            ),
          )
          as _i3.StreamChannel<S>);
}

/// A class which mocks [WebSocketSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketSink extends _i1.Mock implements _i2.WebSocketSink {
  MockWebSocketSink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<dynamic> get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> close([int? closeCode, String? closeReason]) =>
      (super.noSuchMethod(
            Invocation.method(#close, [closeCode, closeReason]),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  void add(dynamic data) => super.noSuchMethod(
    Invocation.method(#add, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<dynamic> addStream(_i7.Stream<dynamic>? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);
}

/// A class which mocks [RTCPeerConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCPeerConnection extends _i1.Mock implements _i4.RTCPeerConnection {
  MockRTCPeerConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get getConfiguration =>
      (super.noSuchMethod(
            Invocation.getter(#getConfiguration),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.Future<List<_i4.RTCRtpSender>> get senders =>
      (super.noSuchMethod(
            Invocation.getter(#senders),
            returnValue: _i7.Future<List<_i4.RTCRtpSender>>.value(
              <_i4.RTCRtpSender>[],
            ),
          )
          as _i7.Future<List<_i4.RTCRtpSender>>);

  @override
  _i7.Future<List<_i4.RTCRtpReceiver>> get receivers =>
      (super.noSuchMethod(
            Invocation.getter(#receivers),
            returnValue: _i7.Future<List<_i4.RTCRtpReceiver>>.value(
              <_i4.RTCRtpReceiver>[],
            ),
          )
          as _i7.Future<List<_i4.RTCRtpReceiver>>);

  @override
  _i7.Future<List<_i4.RTCRtpTransceiver>> get transceivers =>
      (super.noSuchMethod(
            Invocation.getter(#transceivers),
            returnValue: _i7.Future<List<_i4.RTCRtpTransceiver>>.value(
              <_i4.RTCRtpTransceiver>[],
            ),
          )
          as _i7.Future<List<_i4.RTCRtpTransceiver>>);

  @override
  set onSignalingState(dynamic Function(_i4.RTCSignalingState)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSignalingState, value),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionState(dynamic Function(_i4.RTCPeerConnectionState)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionState, value),
        returnValueForMissingStub: null,
      );

  @override
  set onIceGatheringState(dynamic Function(_i4.RTCIceGatheringState)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onIceGatheringState, value),
        returnValueForMissingStub: null,
      );

  @override
  set onIceConnectionState(
    dynamic Function(_i4.RTCIceConnectionState)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onIceConnectionState, value),
    returnValueForMissingStub: null,
  );

  @override
  set onIceCandidate(dynamic Function(_i4.RTCIceCandidate)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onIceCandidate, value),
        returnValueForMissingStub: null,
      );

  @override
  set onAddStream(dynamic Function(_i4.MediaStream)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onAddStream, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoveStream(dynamic Function(_i4.MediaStream)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoveStream, value),
        returnValueForMissingStub: null,
      );

  @override
  set onAddTrack(
    dynamic Function(_i4.MediaStream, _i4.MediaStreamTrack)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onAddTrack, value),
    returnValueForMissingStub: null,
  );

  @override
  set onRemoveTrack(
    dynamic Function(_i4.MediaStream, _i4.MediaStreamTrack)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onRemoveTrack, value),
    returnValueForMissingStub: null,
  );

  @override
  set onDataChannel(dynamic Function(_i4.RTCDataChannel)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onDataChannel, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRenegotiationNeeded(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onRenegotiationNeeded, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrack(dynamic Function(_i4.RTCTrackEvent)? value) => super.noSuchMethod(
    Invocation.setter(#onTrack, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i4.RTCSignalingState?> getSignalingState() =>
      (super.noSuchMethod(
            Invocation.method(#getSignalingState, []),
            returnValue: _i7.Future<_i4.RTCSignalingState?>.value(),
          )
          as _i7.Future<_i4.RTCSignalingState?>);

  @override
  _i7.Future<_i4.RTCIceGatheringState?> getIceGatheringState() =>
      (super.noSuchMethod(
            Invocation.method(#getIceGatheringState, []),
            returnValue: _i7.Future<_i4.RTCIceGatheringState?>.value(),
          )
          as _i7.Future<_i4.RTCIceGatheringState?>);

  @override
  _i7.Future<_i4.RTCIceConnectionState?> getIceConnectionState() =>
      (super.noSuchMethod(
            Invocation.method(#getIceConnectionState, []),
            returnValue: _i7.Future<_i4.RTCIceConnectionState?>.value(),
          )
          as _i7.Future<_i4.RTCIceConnectionState?>);

  @override
  _i7.Future<_i4.RTCPeerConnectionState?> getConnectionState() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionState, []),
            returnValue: _i7.Future<_i4.RTCPeerConnectionState?>.value(),
          )
          as _i7.Future<_i4.RTCPeerConnectionState?>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setConfiguration(Map<String, dynamic>? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#setConfiguration, [configuration]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.RTCSessionDescription> createOffer([
    Map<String, dynamic>? constraints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, [constraints]),
            returnValue: _i7.Future<_i4.RTCSessionDescription>.value(
              _FakeRTCSessionDescription_2(
                this,
                Invocation.method(#createOffer, [constraints]),
              ),
            ),
          )
          as _i7.Future<_i4.RTCSessionDescription>);

  @override
  _i7.Future<_i4.RTCSessionDescription> createAnswer([
    Map<String, dynamic>? constraints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createAnswer, [constraints]),
            returnValue: _i7.Future<_i4.RTCSessionDescription>.value(
              _FakeRTCSessionDescription_2(
                this,
                Invocation.method(#createAnswer, [constraints]),
              ),
            ),
          )
          as _i7.Future<_i4.RTCSessionDescription>);

  @override
  _i7.Future<void> addStream(_i4.MediaStream? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeStream(_i4.MediaStream? stream) =>
      (super.noSuchMethod(
            Invocation.method(#removeStream, [stream]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.RTCSessionDescription?> getLocalDescription() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalDescription, []),
            returnValue: _i7.Future<_i4.RTCSessionDescription?>.value(),
          )
          as _i7.Future<_i4.RTCSessionDescription?>);

  @override
  _i7.Future<void> setLocalDescription(
    _i4.RTCSessionDescription? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setLocalDescription, [description]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.RTCSessionDescription?> getRemoteDescription() =>
      (super.noSuchMethod(
            Invocation.method(#getRemoteDescription, []),
            returnValue: _i7.Future<_i4.RTCSessionDescription?>.value(),
          )
          as _i7.Future<_i4.RTCSessionDescription?>);

  @override
  _i7.Future<void> setRemoteDescription(
    _i4.RTCSessionDescription? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRemoteDescription, [description]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addCandidate(_i4.RTCIceCandidate? candidate) =>
      (super.noSuchMethod(
            Invocation.method(#addCandidate, [candidate]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.StatsReport>> getStats([_i4.MediaStreamTrack? track]) =>
      (super.noSuchMethod(
            Invocation.method(#getStats, [track]),
            returnValue: _i7.Future<List<_i4.StatsReport>>.value(
              <_i4.StatsReport>[],
            ),
          )
          as _i7.Future<List<_i4.StatsReport>>);

  @override
  List<_i4.MediaStream?> getLocalStreams() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalStreams, []),
            returnValue: <_i4.MediaStream?>[],
          )
          as List<_i4.MediaStream?>);

  @override
  List<_i4.MediaStream?> getRemoteStreams() =>
      (super.noSuchMethod(
            Invocation.method(#getRemoteStreams, []),
            returnValue: <_i4.MediaStream?>[],
          )
          as List<_i4.MediaStream?>);

  @override
  _i7.Future<_i4.RTCDataChannel> createDataChannel(
    String? label,
    _i4.RTCDataChannelInit? dataChannelDict,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createDataChannel, [label, dataChannelDict]),
            returnValue: _i7.Future<_i4.RTCDataChannel>.value(
              _FakeRTCDataChannel_3(
                this,
                Invocation.method(#createDataChannel, [label, dataChannelDict]),
              ),
            ),
          )
          as _i7.Future<_i4.RTCDataChannel>);

  @override
  _i7.Future<void> restartIce() =>
      (super.noSuchMethod(
            Invocation.method(#restartIce, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i4.RTCDTMFSender createDtmfSender(_i4.MediaStreamTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#createDtmfSender, [track]),
            returnValue: _FakeRTCDTMFSender_4(
              this,
              Invocation.method(#createDtmfSender, [track]),
            ),
          )
          as _i4.RTCDTMFSender);

  @override
  _i7.Future<List<_i4.RTCRtpSender>> getSenders() =>
      (super.noSuchMethod(
            Invocation.method(#getSenders, []),
            returnValue: _i7.Future<List<_i4.RTCRtpSender>>.value(
              <_i4.RTCRtpSender>[],
            ),
          )
          as _i7.Future<List<_i4.RTCRtpSender>>);

  @override
  _i7.Future<List<_i4.RTCRtpReceiver>> getReceivers() =>
      (super.noSuchMethod(
            Invocation.method(#getReceivers, []),
            returnValue: _i7.Future<List<_i4.RTCRtpReceiver>>.value(
              <_i4.RTCRtpReceiver>[],
            ),
          )
          as _i7.Future<List<_i4.RTCRtpReceiver>>);

  @override
  _i7.Future<List<_i4.RTCRtpTransceiver>> getTransceivers() =>
      (super.noSuchMethod(
            Invocation.method(#getTransceivers, []),
            returnValue: _i7.Future<List<_i4.RTCRtpTransceiver>>.value(
              <_i4.RTCRtpTransceiver>[],
            ),
          )
          as _i7.Future<List<_i4.RTCRtpTransceiver>>);

  @override
  _i7.Future<_i4.RTCRtpSender> addTrack(
    _i4.MediaStreamTrack? track, [
    _i4.MediaStream? stream,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#addTrack, [track, stream]),
            returnValue: _i7.Future<_i4.RTCRtpSender>.value(
              _FakeRTCRtpSender_5(
                this,
                Invocation.method(#addTrack, [track, stream]),
              ),
            ),
          )
          as _i7.Future<_i4.RTCRtpSender>);

  @override
  _i7.Future<bool> removeTrack(_i4.RTCRtpSender? sender) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrack, [sender]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i4.RTCRtpTransceiver> addTransceiver({
    _i4.MediaStreamTrack? track,
    _i4.RTCRtpMediaType? kind,
    _i4.RTCRtpTransceiverInit? init,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTransceiver, [], {
              #track: track,
              #kind: kind,
              #init: init,
            }),
            returnValue: _i7.Future<_i4.RTCRtpTransceiver>.value(
              _FakeRTCRtpTransceiver_6(
                this,
                Invocation.method(#addTransceiver, [], {
                  #track: track,
                  #kind: kind,
                  #init: init,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RTCRtpTransceiver>);
}

/// A class which mocks [MediaStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStream extends _i1.Mock implements _i4.MediaStream {
  MockMediaStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i10.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get ownerTag =>
      (super.noSuchMethod(
            Invocation.getter(#ownerTag),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#ownerTag),
            ),
          )
          as String);

  @override
  set onAddTrack(dynamic Function(_i4.MediaStreamTrack)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onAddTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoveTrack(dynamic Function(_i4.MediaStreamTrack)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoveTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> getMediaTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getMediaTracks, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addTrack(
    _i4.MediaStreamTrack? track, {
    bool? addToNative = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTrack, [track], {#addToNative: addToNative}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeTrack(
    _i4.MediaStreamTrack? track, {
    bool? removeFromNative = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #removeTrack,
              [track],
              {#removeFromNative: removeFromNative},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i4.MediaStreamTrack> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: <_i4.MediaStreamTrack>[],
          )
          as List<_i4.MediaStreamTrack>);

  @override
  List<_i4.MediaStreamTrack> getAudioTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioTracks, []),
            returnValue: <_i4.MediaStreamTrack>[],
          )
          as List<_i4.MediaStreamTrack>);

  @override
  List<_i4.MediaStreamTrack> getVideoTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoTracks, []),
            returnValue: <_i4.MediaStreamTrack>[],
          )
          as List<_i4.MediaStreamTrack>);

  @override
  _i4.MediaStreamTrack? getTrackById(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#getTrackById, [trackId]))
          as _i4.MediaStreamTrack?);

  @override
  _i7.Future<_i4.MediaStream> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i7.Future<_i4.MediaStream>.value(
              _FakeMediaStream_7(this, Invocation.method(#clone, [])),
            ),
          )
          as _i7.Future<_i4.MediaStream>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [MediaStreamTrack].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStreamTrack extends _i1.Mock implements _i4.MediaStreamTrack {
  MockMediaStreamTrack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled =>
      (super.noSuchMethod(Invocation.getter(#enabled), returnValue: false)
          as bool);

  @override
  set onMute(_i4.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onUnMute(_i4.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onUnMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onEnded(_i4.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onEnded, value),
    returnValueForMissingStub: null,
  );

  @override
  set enabled(bool? b) => super.noSuchMethod(
    Invocation.setter(#enabled, b),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getConstraints() =>
      (super.noSuchMethod(
            Invocation.method(#getConstraints, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.Future<void> applyConstraints([Map<String, dynamic>? constraints]) =>
      (super.noSuchMethod(
            Invocation.method(#applyConstraints, [constraints]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.MediaStreamTrack> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i7.Future<_i4.MediaStreamTrack>.value(
              _FakeMediaStreamTrack_8(this, Invocation.method(#clone, [])),
            ),
          )
          as _i7.Future<_i4.MediaStreamTrack>);

  @override
  _i7.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, dynamic> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.Future<bool> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> adaptRes(int? width, int? height) =>
      (super.noSuchMethod(
            Invocation.method(#adaptRes, [width, height]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void enableSpeakerphone(bool? enable) => super.noSuchMethod(
    Invocation.method(#enableSpeakerphone, [enable]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i11.ByteBuffer> captureFrame() =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, []),
            returnValue: _i7.Future<_i11.ByteBuffer>.value(
              _i10.dummyValue<_i11.ByteBuffer>(
                this,
                Invocation.method(#captureFrame, []),
              ),
            ),
          )
          as _i7.Future<_i11.ByteBuffer>);

  @override
  _i7.Future<bool> hasTorch() =>
      (super.noSuchMethod(
            Invocation.method(#hasTorch, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setTorch(bool? torch) =>
      (super.noSuchMethod(
            Invocation.method(#setTorch, [torch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [RTCVideoRenderer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCVideoRenderer extends _i1.Mock implements _i4.RTCVideoRenderer {
  MockRTCVideoRenderer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get videoWidth =>
      (super.noSuchMethod(Invocation.getter(#videoWidth), returnValue: 0)
          as int);

  @override
  int get videoHeight =>
      (super.noSuchMethod(Invocation.getter(#videoHeight), returnValue: 0)
          as int);

  @override
  bool get renderVideo =>
      (super.noSuchMethod(Invocation.getter(#renderVideo), returnValue: false)
          as bool);

  @override
  bool get muted =>
      (super.noSuchMethod(Invocation.getter(#muted), returnValue: false)
          as bool);

  @override
  set onResize(Function? value) => super.noSuchMethod(
    Invocation.setter(#onResize, value),
    returnValueForMissingStub: null,
  );

  @override
  set onFirstFrameRendered(Function? value) => super.noSuchMethod(
    Invocation.setter(#onFirstFrameRendered, value),
    returnValueForMissingStub: null,
  );

  @override
  set srcObject(_i4.MediaStream? stream) => super.noSuchMethod(
    Invocation.setter(#srcObject, stream),
    returnValueForMissingStub: null,
  );

  @override
  set muted(bool? mute) => super.noSuchMethod(
    Invocation.setter(#muted, mute),
    returnValueForMissingStub: null,
  );

  @override
  _i4.RTCVideoValue get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeRTCVideoValue_9(this, Invocation.getter(#value)),
          )
          as _i4.RTCVideoValue);

  @override
  set value(_i4.RTCVideoValue? newValue) => super.noSuchMethod(
    Invocation.setter(#value, newValue),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSrcObject({_i4.MediaStream? stream, String? trackId}) =>
      (super.noSuchMethod(
            Invocation.method(#setSrcObject, [], {
              #stream: stream,
              #trackId: trackId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void eventListener(dynamic event) => super.noSuchMethod(
    Invocation.method(#eventListener, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void errorListener(Object? obj) => super.noSuchMethod(
    Invocation.method(#errorListener, [obj]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> audioOutput(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#audioOutput, [deviceId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setVolume(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RTCSessionDescription].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCSessionDescription extends _i1.Mock
    implements _i4.RTCSessionDescription {
  MockRTCSessionDescription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set sdp(String? value) => super.noSuchMethod(
    Invocation.setter(#sdp, value),
    returnValueForMissingStub: null,
  );

  @override
  set type(String? value) => super.noSuchMethod(
    Invocation.setter(#type, value),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RTCIceCandidate].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCIceCandidate extends _i1.Mock implements _i4.RTCIceCandidate {
  MockRTCIceCandidate() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [PermissionWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionWrapper extends _i1.Mock implements _i13.PermissionWrapper {
  MockPermissionWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i14.PermissionStatus> requestMicrophone() =>
      (super.noSuchMethod(
            Invocation.method(#requestMicrophone, []),
            returnValue: _i7.Future<_i14.PermissionStatus>.value(
              _i14.PermissionStatus.denied,
            ),
          )
          as _i7.Future<_i14.PermissionStatus>);
}

/// A class which mocks [WebRTCWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebRTCWrapper extends _i1.Mock implements _i13.WebRTCWrapper {
  MockWebRTCWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.MediaStream> getUserMedia(
    Map<String, dynamic>? mediaConstraints,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMedia, [mediaConstraints]),
            returnValue: _i7.Future<_i4.MediaStream>.value(
              _FakeMediaStream_7(
                this,
                Invocation.method(#getUserMedia, [mediaConstraints]),
              ),
            ),
          )
          as _i7.Future<_i4.MediaStream>);

  @override
  _i7.Future<_i4.RTCPeerConnection> createPeerConnection(
    Map<String, dynamic>? configuration, [
    Map<String, dynamic>? constraints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createPeerConnection, [
              configuration,
              constraints,
            ]),
            returnValue: _i7.Future<_i4.RTCPeerConnection>.value(
              _FakeRTCPeerConnection_10(
                this,
                Invocation.method(#createPeerConnection, [
                  configuration,
                  constraints,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.RTCPeerConnection>);
}

/// A class which mocks [FirebaseAuthWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthWrapper extends _i1.Mock
    implements _i13.FirebaseAuthWrapper {
  MockFirebaseAuthWrapper() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i5.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i5.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_11(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i5.UserMetadata);

  @override
  List<_i5.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i5.UserInfo>[],
          )
          as List<_i5.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i10.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i5.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_12(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i5.MultiFactor);

  @override
  _i7.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i5.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i7.Future<_i5.IdTokenResult>.value(
              _FakeIdTokenResult_13(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i7.Future<_i5.IdTokenResult>);

  @override
  _i7.Future<_i5.UserCredential> linkWithCredential(
    _i5.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_14(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> linkWithProvider(_i5.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_14(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> reauthenticateWithProvider(
    _i5.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_14(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> reauthenticateWithPopup(
    _i5.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_14(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> reauthenticateWithRedirect(_i5.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.UserCredential> linkWithPopup(_i5.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_14(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> linkWithRedirect(_i5.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i5.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i7.Future<_i5.ConfirmationResult>.value(
              _FakeConfirmationResult_15(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.ConfirmationResult>);

  @override
  _i7.Future<_i5.UserCredential> reauthenticateWithCredential(
    _i5.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_14(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendEmailVerification([
    _i5.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i7.Future<_i5.User>.value(
              _FakeUser_16(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i7.Future<_i5.User>);

  @override
  _i7.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhoneNumber(
    _i5.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i5.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [RTCRtpSender].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCRtpSender extends _i1.Mock implements _i4.RTCRtpSender {
  MockRTCRtpSender() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RTCRtpParameters get parameters =>
      (super.noSuchMethod(
            Invocation.getter(#parameters),
            returnValue: _FakeRTCRtpParameters_17(
              this,
              Invocation.getter(#parameters),
            ),
          )
          as _i4.RTCRtpParameters);

  @override
  String get senderId =>
      (super.noSuchMethod(
            Invocation.getter(#senderId),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#senderId),
            ),
          )
          as String);

  @override
  bool get ownsTrack =>
      (super.noSuchMethod(Invocation.getter(#ownsTrack), returnValue: false)
          as bool);

  @override
  _i4.RTCDTMFSender get dtmfSender =>
      (super.noSuchMethod(
            Invocation.getter(#dtmfSender),
            returnValue: _FakeRTCDTMFSender_4(
              this,
              Invocation.getter(#dtmfSender),
            ),
          )
          as _i4.RTCDTMFSender);

  @override
  _i7.Future<bool> setParameters(_i4.RTCRtpParameters? parameters) =>
      (super.noSuchMethod(
            Invocation.method(#setParameters, [parameters]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> replaceTrack(_i4.MediaStreamTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#replaceTrack, [track]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setTrack(
    _i4.MediaStreamTrack? track, {
    bool? takeOwnership = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setTrack,
              [track],
              {#takeOwnership: takeOwnership},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.StatsReport>> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: _i7.Future<List<_i4.StatsReport>>.value(
              <_i4.StatsReport>[],
            ),
          )
          as _i7.Future<List<_i4.StatsReport>>);

  @override
  _i7.Future<void> setStreams(List<_i4.MediaStream>? streams) =>
      (super.noSuchMethod(
            Invocation.method(#setStreams, [streams]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
