# Config file for SAN for self-signed CA certificate

[req]
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
CN = Fides Dev CA

[v3_ca]
basicConstraints = CA:TRUE
keyUsage = keyCertSign, cRLSign
subjectKeyIdentifier = hash

[v3_req]
subjectAltName = @alt_names
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

# Add here the IP Address where the server will be reachable
[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
IP.2 = ::1
IP.3 = 192.168.178.124
IP.4 = 192.168.0.160
IP.5 = 10.0.2.2