name: Build ConnectX APK in Dev Container

on:
  push:
    branches: [main]
    paths:
      - 'connectx/**'
      - '.github/workflows/connectx-test.yml'
  pull_request:
    paths:
      - 'connectx/**'
      - '.github/workflows/connectx-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd ./connectx
            cp ./template.env .env
            flutter build apk